### ISSUE TITLE
Allow custom templates for reports

### ISSUE THREAD

**Issue by eikes** [pivotal/LicenseFinder#145]
It would be great if I could pass in a path to an .erb file which would then be used to create the report in stead of the standard file. Or is there a way to customize the output other than forking the gem and changing the templates?

**Comment by flavorjones** [comment]
Hi,

We're trying to de-emphasize the report-generation bits of License Finder, as that tends to be the piece that needs the most customization.

Have you tried using the `report` functionality to emit CSV and use that as a data source for your report templating engine? That's what I'd do; and let us know if there's additional information we can provide in the CSV in order to fill out your report.

Please let us know how you get on!

**Comment by eikes** [comment]
I ended up forking and changing the template to my needs. Adding another step in between seems overly complicated to me.

**Comment by mainej** [comment]
@eikes Rather than forking, it's actually pretty easy to write a script that does what `license_finder report` does, but with a different ERB template.  Use the code in [this gist](https://gist.github.com/mainej/b190d2f138c2b9e2e20a) as a starting point.

**Comment by eikes** [comment]
That's neat. Thank you @mainej

**Comment by mainej** [comment]
@eikes ... I made a small update so custom ERB reports are easier.  See the [revised gist](https://gist.github.com/mainej/b190d2f138c2b9e2e20a).  You'll have to pin to the master branch on github.
