### ISSUE TITLE
Report.rb sort_by crash if null dependency is found

### ISSUE THREAD

**Issue by slimjim2234** [pivotal/LicenseFinder#146]
/Users/myuser/.rvm/gems/ruby-2.2.0/gems/license_finder-2.0.3/lib/license_finder/report.rb:16:in `sort_by': comparison of NilClass with String failed (ArgumentError)

One of the dependencies that was extracted from gradle was null.  This could be a bigger issue than just trying to sort a null value, but I temporarily worked around it on my host machine by removing ".sort_by (&:name)" after dependencies on line 16 in report.rb

**Comment by mainej** [comment]
That's definitely a bigger issue.  Can you provide a (preferably minimal) `build.gradle` that would replicate this?

**Comment by nkoterba** [comment]
I'm encountering the same issue and I think I've tracked it down to including file-based libs in a gradle build file.

Here is a minimal `build.gradle` file that should cause the issue:
```javascript
plugins {
    id "com.github.hierynomus.license" version "0.11.0"
}

repositories {
        mavenCentral()
}

apply plugin: 'java'

dependencies {
        compile(
                "com.google.guava:guava:18.0"
        )

        // Import external libraries that are **not** available to download via repo
        compile fileTree(dir: 'libs', include: '*.jar')
}
```

Assume that the 'libs' directory is in the same directory as the `build.gradle` file and contains some `*.jar` files we need to compile our Java-based project.

I imagine that LicenseFinder is failing because it does **not** know how to handle `*.jar` files included in the compile dependency list since these are files without any license information and no easy way to look up necessary license meta-data.

If I remove the Google Guava dependency, LicenseFinder does not crash, but prints out the following:
```javascript
nk-mbp:licenseFinderGradle a$ license_finder report
, , unknown
, , unknown
```

My "guess" is that when you have a `build.gradle` file with compiles using Maven-based dependencies and also file-based dependencies, the sort function is failing because when it hits those file dependencies and they are returning NilClass for Dependency Name and Dependency Version, those are then later being compared against dependencies that do return valid names and versions as Strings.  As the error says, `sort_by` cannot compare NilClass and String.

If I comment out the `compile fileTree(dir: 'libs', include: '*.jar')` from the `build.gradle` file, LicenseFinder works as expected:
```javascript
nk-mbp:licenseFinderGradle a$ license_finder report
guava, 18.0, "Apache 2.0"
```

**Comment by nkoterba** [comment]
Until this gets resolved, I've followed @slimjim2234 suggestion and commented out the sort code otherwise many of my license_finder scripts fail.

Perhaps list the `jar` name as the library name and for version put unknown ?  

Also, I know report can generate other additional columns so default values for those for file-based dependencies would be good too I think.

**Comment by mainej** [comment]
Thanks for the detailed report! That should make it much easier to reproduce.  It makes sense that the error only happens when you have at least one dependency with a name and at least one without.

Also, I like the suggestion about using the name of the jar file as the package name.
