### ISSUE TITLE
Get up and running on Appveyor

### ISSUE THREAD

**Issue by flavorjones** [pivotal/LicenseFinder#174]
Appveyor allows us to test for Windows support, to avoid problems like the one solved by #173.

**Comment by sschuberth** [comment]
Despite this being closed, AppVeyor builds do not pass tests right now due to several issues. After a break, I just wanted to continue working on this again, but I realized @xtreme-vikram-yadav removed the `ci/install_*.sh` scripts in eae74c029ad5e70328602a07c3028feeee9fb813 in favor of a Docker file. However, Windows / AppVeyor does not support Docker natively.

So, what's the plan going forward to support CI on Windows? If the plan is to exclusively use Concourse in the future, does that support Windows?

**Comment by flavorjones** [comment]
Concourse does support windows. Not sure what @kdykeman and team are planning for here, but I'd like to refactor the concourse setup to use https://github.com/flavorjones/concourse-gem and a windows worker like the pipelines at ci.nokogiri.org.

**Comment by sschuberth** [comment]
> Concourse does support windows.

Interesting. From what I understand, Concourse requires self-hosting, and there's no public service for OSS projects like for Travis / AppVeyor, correct?

In any case, I'll submit my fixes to make tests pass on Windows in general.

**Comment by flavorjones** [comment]
> Concourse requires self-hosting, and there's no public service for OSS projects

Also correct. The tradeoff, though, is that you get a ton of flexibility in how and what you run in the pipelines. I'll point again at https://ci.nokogiri.org/ in which Nokogiri is tested under a wide range of situations, including under valgrind; on windows; and (not publicly visible) on OSX. This flexiblity is occasionally necessary and useful.

For example, on LicenseFinder, we found it extraordinarily difficult to set up a working erlang/elixir environment on Travis to support merging https://github.com/pivotal/LicenseFinder/pull/261. That path is now open to us with Concourse.

**Comment by kdykeman** [comment]
There is a story to stand up a windows concourse worker, but we haven't gotten to it yet.  I have to admit, I was somewhat hoping to see a PR come in from others for that.

**Comment by flavorjones** [comment]
@kdykeman I can PR a windows test task into the pipeline. It's on my TODO list.

**Comment by sschuberth** [comment]
More Windows test fixes are in https://github.com/pivotal/LicenseFinder/pull/294. I believe there's only one more issue on Windows, but I'll double-check one Concourse is running on Windows.

BTW, I have some local improvements to `appveyor.yml`. Are you interested in getting these merged, or will `appveyor.yml` go away in favor of Concourse anyway soon?

**Comment by flavorjones** [comment]
If you have changes to `appveyor.yml` I'm sure they'd be welcome.

But Appveyor is limited in the same ways that Travis is, and so we may have to run an abbreviated test suite on those platforms once we pull in additional support (like erlang/elixir above).

**Comment by sschuberth** [comment]
The "problem" with my `appveyor.yml` changes is that they require to restore the `ci/install_*` scripts that were removed in eae74c0, and I guess you'd not want that, or?

**Comment by sschuberth** [comment]
@kdykeman, while I'm not actively using LicenseFinder anymore, I'm willing to help WRT Windows support! I'll start filing a few PRs, starting with https://github.com/pivotal/LicenseFinder/pull/353.

**Comment by kdykeman** [comment]
Excellent! Very much appreciated!

**Comment by sschuberth** [comment]
@kdykeman, I've figured out why the Bower feature test fails on Windows, but I'm unsure how to solve it. On Windows I get

    Dependencies that need approval:
    gmaps, 0.2.30, "This package is not installed. Please install to determine licenses."

So `gmaps` is not installed. But isn't LicenseFinder supposed to install it automatically in order to check the license? Is it pure coincidence that the `gmaps` seems to be installed on Linux, or do you explicitly do that somewhere?

**Comment by sschuberth** [comment]
@kdykeman Any comment on my `gmaps` question above?

**Comment by kdykeman** [comment]
@sschuberth Sorry, I missed your `gmaps` question until now. I'll need to dig into it a bit.
