### ISSUE TITLE
Doesn't keep track of gem versions

### ISSUE THREAD

**Issue by Dbz** [pivotal/LicenseFinder#214]
This is a great gem, but it doesn't keep track of the gem version. When we approve a gem, it is only for a specific version, so if the gem gets updated, then the updated version is not approved. However, LicenseFinder doesn't keep track of gem version changes, so it will continue to list the gem as approved.

**Comment by micfan** [comment]
@Dbz Any PR?

**Comment by flavorjones** [comment]
@Dbz Thanks for asking this question.

Can you help me understand why re-approval of a license is necessary if a gem's license hasn't changed?

The approval process workflow in LicenseFinder is intended to support approvals of licenses; it was not intended to support approvals of specific versions of dependencies, which is what it sounds like you're asking for.

At the moment, I don't think approval of dependencies belongs within LicenseFinder, particularly since the introduction of whitelists to indicate no human action is necessary.

If you think there's a compelling reason to extend the scope of LicenseFinder, I'm happy to discuss this further, but I will need to better understand the rationale.

**Comment by flavorjones** [comment]
Closing, pending a fruitful conversation with the original poster.

**Comment by Dbz** [comment]
I apologize for not responding. I think you bring up a valid point in that the purpose of this gem is to keep track of 'gemfile gem' licenses. The main reason why I wanted to extend the scope of the gem is that my team can not change gem versions unless approved by security. That involves looking at the license on the gem and the licenses of the dependencies. Therefore, if a gem version or dependency changes, we need to get the gem re-approved. I agree my change is out of scope for this gem, so unless someone comments on this issue with a better argument than mine, it should remain closed.

**Comment by flavorjones** [comment]
@Dbz Thanks for following up.

A hacky way to do this might be to emit a report (`license_finder report` command) and check that into your SCM; then you have a record of the versions of all dependencies used. Let me know how you get on.

**Comment by Dbz** [comment]
Awesome. Thank you 👍
