### ISSUE TITLE
License findings should optionally list the file they're defined in 

### ISSUE THREAD

**Issue by sschuberth** [pivotal/LicenseFinder#234]
In CSV output, it would be handy if one could enable a column that names the package manager's file a specific dependency has been defined in. E.g. if a dependency comes from Gradle, `<path_in_project>/build.gradle` should be shown. This would make it a lot easier to debug where a specific dependency comes from in order to eliminate / replace it in the project's code in case of an unacceptable license.

**Comment by flavorjones** [comment]
I agree, LF needs to do a much better job at surfacing what it's doing and making its output's origins more discoverable.

Originally, I had intended for `--debug` to be this tool, but because of how LF was originally designed (with too much dependency injection, IMHO) this option needs to be implemented many places and has rotted a bit (and never made it into actions like `report`).

**Comment by xtreme-shane-lattanzio** [comment]
It looks like this is supported with the columns command line option. Closing this for now.
