### ISSUE TITLE
Ability to exclude an entire package manager

### ISSUE THREAD

**Issue by nevinera** [pivotal/LicenseFinder#271]
We use `npm` for our build tooling and `bower` for included libraries - as such, we care about the licensing on our bower packages and not on our npm packages. `license_finder` takes 45 seconds to run on our repository, which is three times longer than the test suite; by far the bulk of that is checking npm packages. I'd like to allow for a `--only bower` (or `--only npm`) option.

If there's already some way to do what I'm trying to accomplish, let me know - otherwise I'm happy to PR this change.

**Comment by mainej** [comment]
A simple (and only slightly hacky) solution is to move `package.json` elsewhere before running `license_finder`. That'll trick it into ignoring NPM.

Arguably harder (and more hacky) would be to monkey-patch `LicenseFinder::NPM#active?` to always return `false`.  To do that you'll have to use LicenseFinder as a ruby library, not via the CLI, which is briefly described [here](https://gist.github.com/mainej/48ac616844505d50f510). After doing the monkey-patch, to use it in CI you'd need to `exit(lf.unapproved.length)`. To use it for other activities (generating reports, etc.) you'd have to explore the `LicenseFinder::Core` api more.  The [cli code](https://github.com/pivotal/LicenseFinder/tree/master/lib/license_finder/cli) mostly calls `LicenseFinder::Core` or things that hang off it.

Of course, a PR that allows enabling/disabling package managers could work... depends on how much effort you want to put into it.

**Comment by LukeWinikates** [comment]
@nevinera -- if you're still looking for a solution to this, one option might be to ignore both the `dependencies` group and the `devDependencies` groups, which should ignore all of the npm dependencies.

Reading between the lines, if you're not interested in checking the licenses of your npm dependencies because you're not distributing them or using them at runtime (unlike the bower dependencies), maybe installing them as `devDependencies` using `npm install --save-dev` makes semantic sense. Then you could `license_finder ignored_groups add devDependencies`. That was my situation and my solution on the last npm + bower project I worked on.

**Comment by nevinera** [comment]
That sounds like a solid solution, thanks!

**Comment by tourea** [comment]
This is valid use case and we should consider re-opening it. In my case, I need to exclude `pip` since we don't ship python
