### ISSUE TITLE
LicenseFinder reports `[Circular]` license for some node modules

### ISSUE THREAD

**Issue by atomanyih** [pivotal/LicenseFinder#307]
Given this package.json:
```json
{
  "name": "license_finder_test",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "node-polyglot": "^2.0.0"
  },
  "devDependencies": {
    "enzyme": "^2.8.2"
  },
  "scripts": {
  },
  "repository": {
  },
  "author": "",
  "license": "MIT",
  "bugs": {
  },
  "private": true,
  "engines": {
    "node": "^6.11.0",
    "yarn": "^0.24.6",
    "npm": "^5.0.3"
  }
}
```

running `license_finder` reports the wrong license for two libraries:
```
function-bind, 1.1.0, [Circular]
has, 1.0.1, [Circular]
```

Using `yarn why` we've got this info:

```
$ yarn why function-bind

info Reasons this module exists
   - "node-polyglot#has" depends on it
   - "enzyme#function.prototype.name" depends on it
```

```
$ yarn why has

info This module exists because "node-polyglot" depends on it.
```

If we remove either `node-polyglot` or `enzyme` from `package.json` it correctly shows determines the licenses are `MIT`

----

Some other background:

We're pointed at master because #301 breaks `license_finder` on most of our workstations

Excerpt from our `Gemfile`:

```
 gem 'license_finder', github: 'pivotal/LicenseFinder', ref: '2b5562f5547e3e716e3bc33917db8e9851a6c0aa'
```

**Comment by ryanmattcollins** [comment]
Fixed! It's an issue with newer versions of node (which we were behind on).

https://github.com/pivotal/LicenseFinder/commit/a6c03101c4646c2108b6380cab54fc5a047106f0

**Comment by kdykeman** [comment]
What's interesting about this one is that LicenseFinder relies on the output (i.e. stdout) from external package managers to obtain information about the dependency tree. In some cases, stdout may not be thought of as a contract/API, and because LicenseFinder doesn't currently change behaviors for different versions of a given package manager, there's an implicit dependency on a set of package manager versions that output the expected format.

For now, the interim solution when it comes up for a new package manager version would be to try running LicenseFinder against your project using the Docker container which contains one of the supported versions of the external tools.
