### ISSUE TITLE
Ant project licenseFinder

### ISSUE THREAD

**Issue by AJJJAIAH** [pivotal/LicenseFinder#436]
Hello,

May I know how to get license-finder report for ant projects?

thanks,
Ajjaiah

**Comment by kdykeman** [comment]
Hi @AJJJAIAH,

Unfortunately, license-finder doesn't currently support Ant projects. It's been a while since I've used Ant myself, but briefly looking around, it looks like the [report task](http://ant.apache.org/ivy/history/2.1.0/use/report.html) might help gather some of the information you're likely after.

In case you or somebody you know is interested in contributing in order to add support for Ant, we've recently updated [Contributing.md](https://github.com/pivotal/LicenseFinder/blob/10aa2be6f2c9d8b117c1808e9e0309e46fbd7c85/CONTRIBUTING.md).
