### ISSUE TITLE
Clarification of actions required for private gems

### ISSUE THREAD

**Issue by hlascelles** [pivotal/LicenseFinder#742]
We have a mono-repo with private projects which are gems, and each has a gemspec.

The [official gemspec documentation](https://guides.rubygems.org/specification-reference/#license=) says that "Not specifying a license means all rights are reserved; others have no rights to use the code for any purpose.".

This works fine, but it does mean that every time we add a new project, `license_finder` will complain as the licence is missing, and the project is not known. We can of course add an approval for the project with:

`license_finder approvals add foo --decisions_file ./license_finder.yaml --who "Me" --why "Internal source code"`

That works too, but is an extra step when adding a new project.

We also tried adding a new license, "<Company Name> Proprietary", and just approving that, but we then are (may?) not be following gemspec guidance.

So my questions:

1) Would you be open to a PR to allow `license_finder` to ignore gems found in a directory? (So we make all our internal gemspecs have no license set).
2) Is it desirable/intentional that new unexpected projects with (correctly) no licence should be approved individually?
3) Something else

Related rubygems issue: https://github.com/rubygems/rubygems/issues/3665

**Comment by xtreme-shane-lattanzio** [comment]
Hi @hlascelles! Thanks for your questions!

We have been talking about possible including a way to ignore paths, more than just for ruby projects so I would be open to see what that looks like at the very least.

As for you question about desired functionality, I think that this is more just an edge case that has never been handled. LF does not look for guidance depending on different package managers and I am hesitant to write this into LF because that guidance can change at any time. We would then need to make changes in response to that.

 I think the way it is now is acceptable i.e have them still report that there are no licenses specified. Users could then be able to write a quick script to filter those out themselves. This also allows users to have more control and insight into the licenses instead of magic happening behind the scenes to approve. That is also why I like the idea of ignored dependencies more because a user would have to explicitly do that.

Please let me know your thoughts and thanks again for looking into this!

**Comment by hlascelles** [comment]
Yep, makes sense. "Specify no license in the gemspecs" to indicate closed source code, then "make a concious choice" to allow those closed source projects. Sounds good. Cheers!
