### ISSUE TITLE
Error when running with Psych 4.0

### ISSUE THREAD

**Issue by mvz** [pivotal/LicenseFinder#841]
When running `license_finder` in a project that has some dependency decisions, with Psych 4.0 installed, the following error happens:

```
[...]/lib/ruby/gems/3.0.0/gems/psych-4.0.1/lib/psych/class_loader.rb:99:in `find':
  Tried to load unspecified class: Time
```

**Comment by mvz** [comment]
I created a pull request that fixes this.

**Comment by darkhelmet** [comment]
Will the related PR be merged and this fixed any time soon or should I fork and load from our GitHub?

**Comment by jkwuc89** [comment]
I am also running into this issue after upgrading my Rails project to Ruby 3.1.0 and verified that this PR fixes the issue.

**Comment by afstanton** [comment]
I am also having this issue.

**Comment by amilligan** [comment]
@xtreme-jason-smith @xtreme-shane-lattanzio @kmayer Is Tanzu née Pivotal née XtremeLabs via PivotalLabs still maintaining this?  Do you need maintainers?  I'm sure there are some people who would like to help keep this project alive.

The work here appears to be done, someone just needs to commit and release it.  This issue is blocking anyone who wants to update to ruby 3.1.

I apologize if you three are not the people to answer this.  I picked two of you as recent contributors, and @kenmayer as the past maintainer.  If not any of you, who is the right person to talk with?

**Comment by xtreme-jason-smith** [comment]
Hi @amilligan , we have a PR in the pipeline that is going to fix this issue.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @amilligan ! Yes we are still maintaining this but we have had other priorities creep up over the last 6 months. Apologies for the delays. We will be working on official 3.x support for ruby soon. This week I'll be looking at the PRs and issues I've missed over the last little while and will try to get a new version out with as much as I can thanks to community contributions
