### ISSUE TITLE
Docker container does not find either ruby nor license_finder gem

### ISSUE THREAD

**Issue by moeffju** [pivotal/LicenseFinder#895]
Using the `dlf` script from the repo, v 7.0.1:

```
$ ./dlf license_finder
Required ruby-2.6.5 is not installed.
To install do: 'rvm install "ruby-2.6.5"'
/usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem license_finder (>= 0.a) with executable license_finder (Gem::GemNotFoundException)
	from /usr/share/rvm/rubies/ruby-3.1.1/lib/ruby/site_ruby/3.1.0/rubygems.rb:284:in `activate_bin_path'
	from /usr/share/rvm/gems/ruby-3.1.1/bin/license_finder:25:in `<main>'
	from /usr/share/rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `eval'
	from /usr/share/rvm/gems/ruby-3.1.1/bin/ruby_executable_hooks:22:in `<main>'
```

As the README suggested chaining commands ought to work, I also tried:

```
$ ./dlf "rvm install ruby-2.6.5 && license_finder"
Required ruby-2.6.5 is not installed.
To install do: 'rvm install "ruby-2.6.5"'
/bin/bash: rvm install ruby-2.6.5 && license_finder: command not found
```

And finally I tried running just `dlf` and then in the shell running rvm and license_finder, but it still doesn't find the gem binary.

Unfortunately I could not find a lot of documentation for the Docker image, so I'm not sure why it would not find ruby, would not automatically install it, or not find the gem binary.

**Comment by xtreme-shane-lattanzio** [comment]
Hey @moeffju ! Based on what you're saying, this should be a problem with the previous versions as well that do not have ruby 2.6.5 installed. The 7.0.1 docker image comes with ruby 3.1.1 installed by default. If you want to use the LF docker image on an older version of ruby, you can to install that version of ruby with rvm as you have done. However you are missing the step of reinstalling license_finder and the required dependencies for that version of ruby. 

However, I think the proper way is to run `./dlf` from the base LF directory and use the `--project-path` flag to the repo you are trying to scan to ensure the proper dependencies are being used. Something like `./dlf license_finder --project-path=temp`

Does that make sense?

**Comment by moeffju** [comment]
Hmm, I thought about that but didn’t see why cwd vs project-path would make a difference, but I think now that I tried it I believe the `.ruby-version` file in the repo causes it. Since that’s not super uncommon, I wonder how to handle that case (and I was hoping that the docker image would do it automagically 😅) because the way of passing in a quoted command doesn't work, and the workaround of invoking bash -c with a quoted command breaks the rvm integration.

Anyhow, concrete situation in this project: There is a `.ruby-version` file in the project root that sets ruby 2.6.5, and the Gemfile references this as well (through reading the file directly as an argument for the `ruby` tag in the Gemfile). The latter fails naively with `dlf` and `--project-path` because it uses a relative path and looks for `.ruby-version` relative to the dlf root, not the Gemfile itself. That’s something I can fix tho.

**Comment by xtreme-shane-lattanzio** [comment]
@moeffju I think there may have been an issue with the dlf script since November. There was escaping logic that was added. I was confused when running because it looked right but it was because I was fetching info from my local machine and not the docker image. I just pushed a fix and ran `../dlf "rvm install ruby-2.6.5 && gem install license_finder && license_finder"` 

Can you let me know if this solves things for you??

**Comment by moeffju** [comment]
I'll update the script & image and try again tomorrow, thanks!
I will probably also look into optimizing the docker image as it's quite big, and maybe adding a little wrapper that would take care of things like ensuring the right ruby is installed, and so, do you think that's something that would make sense to upstream?

**Comment by xtreme-shane-lattanzio** [comment]
Yes! Sounds good. Looking at docker image size was something that we wanted to do for a while so that would be great. The change I made for dlf was only for the script though. The image would be the same.

Wrappers will also be very useful. Its also great to get feedback from the community because we use the tool for different use cases. We rarely use the LF docker image directly and never use the `dlf` script. I'd be happy to look through any PR that comes up and we would really appreciate any help!!
